[[redirects]]
    from = "/*"
    to = "/404/"
    status = 404

[[redirects]]
    from = "/.well-known/host-meta*"
    to = "https://fed.brid.gy/:splat"
    status = 302

[[redirects]]
    from = "/.well-known/webfinger*"
    to = "https://fed.brid.gy/:splat"
    status = 302

[[plugins]]
    package = "netlify-plugin-11ty"